### ISSUE TITLE
Error starting and adding user

### ISSUE THREAD

**Issue by Horshev** [beaston02/InstaHoarder#2]
Hello!
Download InstaHoarder, added user and password to file config.conf.
When you enter the command
`python3.5 main.py`
I get an error
```
user@linux:~/InstaHoarder$ python3.5 main.py 
logging in
    stories:            0
      posts:            0
      total:            0
Exception in thread Thread-12:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/user/InstaHoarder/classes/insta.py", line 416, in run
    following = Get(self.conf).following(self.r)
  File "/home/user/InstaHoarder/classes/insta.py", line 312, in following
    user_id = self.id_from_username(r,self.config.settings.username)
  File "/home/user/InstaHoarder/classes/insta.py", line 331, in id_from_username
    return int(r.get(url.user.format(user=username)).json()['graphql']['user']['id'])
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Exception in thread Thread-13:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/user/InstaHoarder/classes/insta.py", line 437, in run
    following = Get(self.conf).following(self.r)
  File "/home/user/InstaHoarder/classes/insta.py", line 312, in following
    user_id = self.id_from_username(r,self.config.settings.username)
  File "/home/user/InstaHoarder/classes/insta.py", line 331, in id_from_username
    return int(r.get(url.user.format(user=username)).json()['graphql']['user']['id'])
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    stories:            0
      posts:            0
      total:            0
```

Also there is an error when adding a username
`python3.5 add.py dianova01`
I get an error
```
user@linux:~/InstaHoarder$ python3.5 add.py dianova01
Traceback (most recent call last):
  File "add.py", line 32, in <module>
    add(user)
  File "add.py", line 12, in add
    user_id = get.id_from_username(r, user)
  File "/home/user/InstaHoarder/classes/insta.py", line 331, in id_from_username
    return int(r.get(url.user.format(user=username)).json()['graphql']['user']['id'])
  File "/usr/lib/python3/dist-packages/requests/models.py", line 808, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Help me, please!
Thank you!

**Comment by NandoPrates** [comment]
me too

**Comment by LunarPenguin** [comment]
I just did some investigating and found out that InstaHoarder uses this `https://www.instagram.com/{user}/?__a=1` url for retrieving user info (or at least user id's) and from recent posts online it seems that IG no longer allows you to use that url if you are not logged in, it gives you a `403 (access denied)` error.

The code that accesses that url expects the url to return a json string not a 403 error and because of that it gives the error you posted.

I expect both errors you posted to be caused by the same thing.
